spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CloudStorage
    username: root
    password: 72155757
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: your_secret_key
  expiration: 86400000 # 1 день в миллисекундах

logging:
  level:
    org.springframework: DEBUG